---
- name: Install required packages
  loop:
    - ifupdown
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - floatingip

- name: Write interface config
  notify:
    - Restart networking
  loop: "{{ floatingip_devices }}"
  loop_control:
    label: "{{ item.address }}"
  ansible.builtin.template:
    src: config.j2
    dest: "{{ floatingip_path }}/{{ item.config }}"
    mode: u=rw,g=r,o=r
  tags:
    - floatingip

- name: Delete interface config
  notify:
    - Restart networking
  loop: "{{ floatingip_devices }}"
  loop_control:
    label: "{{ item.address }}"
  when: item.state | default("present") == "absent"
  ansible.builtin.file:
    path: "{{ floatingip_path }}/{{ item.config }}"
    state: absent

...
